### ISSUE TITLE
Division by zero when no data found

### ISSUE THREAD

**Issue by tqvtqv** [noworks/pager-taglib#1]
`java.lang.ArithmeticException: / by zero
    at com.jsptags.navigation.pager.PagerTag.pageNumber(PagerTag.java:334)
    at com.jsptags.navigation.pager.PagerTag.doStartTag(PagerTag.java:372)`

**Comment by izuno4t** [comment]
maxPageItems is required and configured value. Why does division by zero occur?
Configure Example is below.

`<pg:pager url="newsList.do" items="<%=((List)request.getAttribute("newsList")).size()%>" maxIndexPages="10" maxPageItems="10" export="pageOffset,currentPageNumber=pageNumber" scope="request">`

**Comment by izuno4t** [comment]
Fixed 98194d0633b5efcda64b46f3e29b5278c379e748
